### ISSUE TITLE
Receive ex files

### ISSUE THREAD

**Issue by mariusmoe** [mariusmoe/metrics-consumer#26]
## TODO
- [x] Add route for upload of measuresummary
- [x] Add route for upload of ex file
- [x] Add logic for connecting ex with measuresummary
- [x] Only keep one version of ex file 
- [x] Test valid measuresummary and ex file couple
- [ ] Test *INVALID* measuresummary and ex file couple

The server should be able to receive ex files 

### Details
When delivering both measure data and ex files, this has to be done in two separate requests
